#java -cp druid-1.1.6.jar com.alibaba.druid.filter.config.ConfigTools <password>
idgenerator:
  generators:
    idGenerator:
      base-time: 2018-09-06 00:00:00.000
      node-num: 0
    antherOne:
      base-time: 2018-01-01 00:00:00.000
      node-num: 1

httpinvoker:
  httpcomponents:
    httpcomponentsHttpInvoker:
      connection-request-timeout: 60000
      connect-timeout: 60000
      read-timeout: 120000
      max-conn-per-route: 256
      max-conn-total: 2560
      max-idle-time: 1200
  okhttp3:
    okhttp3HttpInvoker:
      connect-timeout: 60000
      read-timeout: 120000
      write-timeout: 60000

server:
  display-name: pem-service
  port: ${port:8070}
  context-path: /pem-service
  connection-timeout: 20000
  session:
    timeout: 2678400
  tomcat:
    accesslog:
      enabled: true
      directory: access-logs
      rename-on-rotate: true
#    basedir: ../tomcat
    max-http-post-size: 104857600 #100MB,50MB:52428800
    max-connections: 10000
    min-spare-threads: 10
    max-threads: 200
    uri-encoding: UTF-8      
    accept-count: 100

dubbo:
  application:
    id: pem-service
    name: pem-service
    qos-enable: false
  registry:
    id: pem-service-registry
    client: curator
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    id: pem-service-protocol
    name: dubbo
    port: 20871
  scan:
    base-packages: com.chmei.**.dubbo.provider,com.chmei.**.dubbo.consumer

spring:
  application:
    name: pem-service
  mandatory-file-encoding: UTF-8
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      force: true
    multipart:
      #location: ../uploadfiles
      max-file-size: 10MB
      max-request-size: 50MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    servlet:
      load-on-startup: 0
    throw-exception-if-no-handler-found: true
  resources:
    static-locations:
    - context:/
    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
    - file:D:/
  redis:
    host: localhost
    password:
    database: 2
    port: 6379
    timeout: 2678400
    pool:
      max-active: 10000
      max-idle: 100
#    cluster:
#      nodes: host:port,host:port,host:port
#      max-redirects: 5

#org/springframework/boot/logging/logback/*.xml，在spring-boot-version.jar里面。
logging:
  config: classpath:logback/logback-spring.xml
  path: ../tomcat/logs
  file: pem-service.log
  level:
    root: INFO

---
spring: 
  profiles: test
  redis:
    host: 127.0.0.1
    password: qazWSXedcRFV
    port: 6379
    database: 2
logging:
   path: ./../pem_log/service

---
spring: 
  profiles: prod
  redis:
    host: 127.0.0.1
    password: 2wsx!QAZZH
    port: 26379
    database: 2
logging:
  path: ./../pem_log/service