#java -cp druid-1.1.6.jar com.alibaba.druid.filter.config.ConfigTools <password>
aliPay:
  app:
    aliPayGateway: https://openapi.alipay.com/gateway.do
    aliPayAppId: 2019092267679412
    rsaPrivatKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCsLSv1SH18WPt4qGYrT4DDY0FanwrRDMg9OCx/bELuMRHnPAc76i6Fe70zduhiTVU78OX41LgCJSGPS1A9b4LTGml8LA8Ky3OZAjj7PtzT378eNKUOZYIKYKhPSa94mb6qd6NqAy2MtgMM06Xok/PeFjIJh5ZDP8okpKvhxzhWavrdQl5RQW26jVgXSxWtpdphZvN4M9oJvP7fgmwejUmJo2xToD/6i9/A6gnjXT62zUFDTvRBPcTzlq4IM4aucFV8juw+DxJ9CQiUMIetvPO5lUa2+IW8HxMtjOLmJxwP2JvC+Jj7GEXiiKoMdZjzoDi97+z9r0Rfr1zvPxMLNjpbAgMBAAECggEAUt+3TewjgovuFwivjN9KskF/PphZA4CsjVMRkA/TM4VpAa1SKhOxaszBqBjvCAoDIcP1Xc09+MJYofl1WOzowqXu6jbm0qJVNOvt83kxn8YN3wMmA4T2j/owaWGlVV5jePf3L1ryPM2LMExbilRUyKxUT2P0/s+gg/zDQvy6cFVnceP+kfWxRoD2gVNMh5hvYp4EENa38+00KJtG1pHV3s525QC95qaaaJi0i6JjAWCd6I0yfKTc2x+bh+ny4CTvu2u01eEMsbu8W5FRqIfwU9QS3Ph7bgSkW1UPlsKtLHz6PZODiJPBZojJwdUDEIaOJce3CiC0vtuzOFs3KzXemQKBgQD1Yw1yIWiGT1EK+70xqeDhP9pv3D3oRTynZ/FLXB+GYHCgo36b5HzIk0alfYBciLKPcTtCO/ifNLMzVcdXKgLrQWcHmv7BNXuOq6LYTBm5mDffmjH6dMSPH2vTYuWQBSwC0ebNpnj9Ng3vGxE605laG8I3Cbg5qUzT6FfQVbP3DwKBgQCzn4ad0zdRB+8GwMLHpOiuWOioqDuiCWhon+FxP8ozgVQvTwq1KGM0wdtYvc9TW/eofI5b9Um+rBTbKyKY0mS7hSHWQoYj5FKAPGeAFgvHX1rlyxVPDOPEtfGknDFGtehgqkGwvml+yOoJ4FXbssOpIEKodVe2oeXmASmI4zCn9QKBgQCmdUgEuOb33UxDoBtqWivDgRZDtWqFappHkXocveRguoEMZ3wWcju3sDhHQMhXfR9rsMsbFiWEkjJRy4mK9mO+hMJIZXsVQ5uKX6H7CjyVKs4UL7xhgt5nnE//uGGzfd6qFwtzS89dLVLsdTcN6cZoWtY3ka9X5iHIyh7vo4OOPwKBgALb0BWk7eVxPeGaob7xpe5YZeOBQemzQqEfokPeIwas0T0rgd0eNm35g9cmtiz6creQu+dEwRaywGY4ioVqG8ZMORyi1GWv1YxK6c7FCwzyPI0ZrU4jw2A3ERBwl+wrKvaW3xLEBQPKiMb9dgBYGPsRE16A95NlgjYl4JZYH0cdAoGBAK9cxaOGijuMFW2Ydka5T2RVRvSDkCyW0G5F/kpu28Q2yL6B8fPTGTuWkuG2g1KR98YGkdnRd3JV2RANU74PRJv0NjZCdZWuWe/OdQtx4AWgVaTajjJLHmCZt20TRcwjm9zmpxDgc/jIsVWyPjYC0ydk6YfVQOvtH/zv6Cmt+dgt
    alipayFormat: json
    alipayCharset: utf-8
    rsaAlipayPublicKey: MIIE4jCCAsqgAwIBAgIIYsSr5bKAMl8wDQYJKoZIhvcNAQELBQAwejELMAkGA1UEBhMCQ04xFjAUBgNVBAoMDUFudCBGaW5hbmNpYWwxIDAeBgNVBAsMF0NlcnRpZmljYXRpb24gQXV0aG9yaXR5MTEwLwYDVQQDDChBbnQgRmluYW5jaWFsIENlcnRpZmljYXRpb24gQXV0aG9yaXR5IFIxMB4XDTE4MDMyMjE0MzQxNVoXDTM3MTEyNjE0MzQxNVowgYIxCzAJBgNVBAYTAkNOMRYwFAYDVQQKDA1BbnQgRmluYW5jaWFsMSAwHgYDVQQLDBdDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTE5MDcGA1UEAwwwQW50IEZpbmFuY2lhbCBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eSBDbGFzcyAyIFIxMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsLMfYaoRoPRbmDcAfXPCmKf43pWRN5yTXa/KJWO0l+mrgQvs89bANEvbDUxlkGwycwtwi5DgBuBgVhLliXu+R9CYgr2dXs8D8Hx/gsggDcyGPLmVrDOnL+dyeauheARZfA3du60fwEwwbGcVIpIxPa/4n3IS/ElxQa6DNgqxh8J9Xwh7qMGl0JK9+bALuxf7B541Gr4p0WENG8fhgjBV4w4ut9eQLOoa1eddOUSZcy46Z7allwowwgt7b5VFfx/P1iKJ3LzBMgkCK7GZ2kiLrL7RiqV+h482J7hkJD+ardoc6LnrHO/hIZymDxok+VH9fVeUdQa29IZKrIDVj65THQIDAQABo2MwYTAfBgNVHSMEGDAWgBRfdLQEwE8HWurlsdsio4dBspzhATAdBgNVHQ4EFgQUSqHkYINtUSAtDPnS8XoyoP9p7qEwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQELBQADggIBAIQ8TzFy4bVIVb8+WhHKCkKNPcJe2EZuIcqvRoi727lZTJOfYy/JzLtckyZYfEI8J0lasZ29wkTta1IjSo+a6XdhudU4ONVBrL70U8Kzntplw/6TBNbLFpp7taRALjUgbCOk4EoBMbeCL0GiYYsTS0mw7xdySzmGQku4GTyqutIGPQwKxSj9iSFw1FCZqr4VP4tyXzMUgc52SzagA6i7AyLedd3tbS6lnR5BL+W9Kx9hwT8L7WANAxQzv/jGldeuSLN8bsTxlOYlsdjmIGu/C9OWblPYGpjQQIRyvs4Cc/mNhrh+14EQgwuemIIFDLOgcD+iISoN8CqegelNcJndFw1PDN6LkVoiHz9p7jzsge8RKay/QW6C03KNDpWZEUCgCUdfHfo8xKeR+LL1cfn24HKJmZt8L/aeRZwZ1jwePXFRVtiXELvgJuM/tJDIFj2KD337iV64fWcKQ/ydDVGqfDZAdcU4hQdsrPWENwPTQPfVPq2NNLMyIH9+WKx9Ed6/WzeZmIy5ZWpX1TtTolo6OJXQFeItMAjHxW/ZSZTok5IS3FuRhExturaInnzjYpx50a6kS34c5+c8hYq7sAtZ/CNLZmBnBCFDaMQqT8xFZJ5uolUaSeXxg7JFY1QsYp5RKvj4SjFwCGKJ2+hPPe9UyyltxOidNtxjaknOCeBHytOr
    signType: RSA2

    alipayBody: 众享信息-余额充值
    alipaySubject: 众享信息
    alipayProductCode: QUICK_MSECURITY_PAY
    alipayNotifyUrl: http://zhongxiang.natapp1.cc/aliPayCallback

wx:
  app:
    # APPID
    appId: wx12953fc5b1c933b8
    # 商户ID
    mchId: 1556830761
    # 商户秘钥
    key: 1zhongxiangkejiyouxiangongsi2019
    # 回调地址
    notifyUrl: http://zhongxiang.natapp1.cc/wxPayCallback
    # 商品描述
    body: 众享信息-余额充值

#id生成策略
idgenerator:
  generators:
    idGenerator:
      base-time: 2018-11-28 00:00:00.000
      node-num: 0
    antherOne:
      base-time: 2018-01-01 00:00:00.000
      node-num: 1

httpinvoker:
  httpcomponents:
    httpcomponentsHttpInvoker:
      connection-request-timeout: 60000
      connect-timeout: 60000
      read-timeout: 120000
      max-conn-per-route: 256
      max-conn-total: 2560
      max-idle-time: 1200
  okhttp3:
    okhttp3HttpInvoker:
      connect-timeout: 60000
      read-timeout: 120000
      write-timeout: 60000


ertaskcodegenerator:
  name: pem:ertaskcode:generator
  init-no: 1
  step: 1
  max-no: 9999

server:
  display-name: pem-data
  port: ${port:8060}
  context-path: /pem-data
  connection-timeout: 20000
  session:
    timeout: 1800
  tomcat:
    accesslog:
      enabled: true
      directory: access-logs
      rename-on-rotate: true
    #    basedir: ../tomcat
    max-http-post-size: 52428800 #50MB
    max-connections: 10000
    min-spare-threads: 10
    max-threads: 200
    uri-encoding: UTF-8
    accept-count: 100

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  executor-type: REUSE
  check-config-location: true

pagehelper:
  helper-dialect: mysql
  offset-as-page-num: "true"
  row-bounds-with-count: "true"
  page-size-zero: "false"
  reasonable: "false"
  params: pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
  support-methods-arguments: "true"
  auto-runtime-dialect: "false"
  close-conn: "true"

dubbo:
  application:
    id: pem-data
    name: pem-data
    qos-enable: false
  registry:
    id: pem-data-registry
    client: curator
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    id: pem-data-protocol
    name: dubbo
    port: 20861
  scan:
    base-packages: com.chmei.**.dubbo.provider,com.chmei.**.dubbo.consumer

spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/pem_manage_db?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
      username: root
      password: GW7AgS9Tsypy8XXmpW5l5n4ZWOyUgUNpxtO7R/l5szVy5I0v3DHPzbXJnZXGLqrPVsmV7A8b0Tlpfp5fur8lyg==
      driver-class-name: com.mysql.jdbc.Driver
      filters: config
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIKbnMEE7ON1C+p57UpDFgtmDptgnVJhI45ah6HTcUeV/SVX+ufJi35FMmSgmQyLxEENCNndUpwcs19Pd9FzpJUCAwEAAQ==
      connection-error-retry-attempts: 0
      initial-size: 1
      max-active: 200
      min-idle: 1
      max-wait: 20000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size:  -1
      max-open-prepared-statements: -1
      validation-query: select 1
      validation-query-timeout: 3
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 1800000
      max-evictable-idle-time-millis: 1800000
  application:
    name: pem-data
  mandatory-file-encoding: UTF-8
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      force: true
    multipart:
      #location: ../uploadfiles
      max-file-size: 10MB
      max-request-size: 50MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    servlet:
      load-on-startup: 0
    throw-exception-if-no-handler-found: true
  resources:
    static-locations:
      - context:/
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      - file:D:/
  #  session:
  #    store-type: REDIS
  #    redis:
  #      flush-mode: ON_SAVE
  #    cleanup:
  #      cron:
  #        expression: ${sessionCleanupCron:0 0/2 * * * ?}
  #  thymeleaf:
  #    cache: false
  #    encoding: UTF-8
  #    mode: HTML
  #    prefix: classpath:/templates/
  #    suffix: .html
  redis:
    host: localhost
    password: 
    database: 2
    port: 6379
    timeout: 3000
    pool:
      max-active: 10000
      max-idle: 100
#    cluster:
#      nodes: host:port,host:port,host:port
#      max-redirects: 5

#org/springframework/boot/logging/logback/*.xml，在spring-boot-version.jar里面。
logging:
  config: classpath:logback/logback-spring.xml
  path: ../tomcat/logs
  file: pem-data.log
  level:
    root: INFO

---
spring:
  profiles: test
  datasource:
    druid:
      url: jdbc:mysql://192.168.0.206:3306/pem_manage_test_db?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
      username: pem_manage_test
      password: a3UrA/FDc2f3fgevxc5vUSzOQdKwa5rf1pSq9EzDMvmMDmty603VkxVDE0DGdWD5XjazVe8QTrTT6XWLhZCcWQ==
      driver-class-name: com.mysql.jdbc.Driver
      filters: config
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANKrKZ37uUZHmLLuVyEWIJB2iUA4PncxM4mMIGw+y9SjTUNl4hy+wv13owIqqXBUmef0O7W4pXD5Z7k8jTAFircCAwEAAQ==
      connection-error-retry-attempts: 0
      initial-size: 1
      max-active: 200
      min-idle: 1
      max-wait: 20000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size:  -1
      max-open-prepared-statements: -1
      validation-query: select 1
      validation-query-timeout: 3
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 1800000
      max-evictable-idle-time-millis: 1800000
  redis:
    host: 127.0.0.1
    password: 1qaz!QAZ
    port: 6379
    database: 2
logging:
  path: ./../pem_log/data

---
spring:
  profiles: prod
  datasource:
    druid:
      url: jdbc:mysql://39.100.26.214:3306/pem_manage_db?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
      username: root
      password: a3UrA/FDc2f3fgevxc5vUSzOQdKwa5rf1pSq9EzDMvmMDmty603VkxVDE0DGdWD5XjazVe8QTrTT6XWLhZCcWQ==
      driver-class-name: com.mysql.jdbc.Driver
      filters: config
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANKrKZ37uUZHmLLuVyEWIJB2iUA4PncxM4mMIGw+y9SjTUNl4hy+wv13owIqqXBUmef0O7W4pXD5Z7k8jTAFircCAwEAAQ==
      connection-error-retry-attempts: 0
      initial-size: 1
      max-active: 200
      min-idle: 1
      max-wait: 20000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size:  -1
      max-open-prepared-statements: -1
      validation-query: select 1
      validation-query-timeout: 3
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 1800000
      max-evictable-idle-time-millis: 1800000
  redis:
    host: 127.0.0.1
    password: 1qaz!QAZ
    port: 6379
    database: 2
logging:
  path: ./../pem_log/data